name = "drs"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "drs_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "drs.wasm"
command = "npm run build:release"
